apiVersion: catalog.tekton.dev/v1alpha1
kind: Catalog
metadata:
  name: catalog-sample
spec:
  # Add fields here
  url: "https://github.com/sthaha/tektoncd-catalog"
  contextPath: "/"
  revision: "master"

