# permissions to do viewer catalogs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: catalog-viewer-role
rules:
- apiGroups:
  - catalog.tekton.dev
  resources:
  - catalogs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - catalog.tekton.dev
  resources:
  - catalogs/status
  verbs:
  - get
