
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - catalog.tekton.dev
  resources:
  - cataloginstalls
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - catalog.tekton.dev
  resources:
  - cataloginstalls/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - catalog.tekton.dev
  resources:
  - catalogs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - catalog.tekton.dev
  resources:
  - catalogs/status
  verbs:
  - get
  - patch
  - update
