apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: db
  name: db
  namespace: tekton-hub-preview
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
