
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  name: catalogs.catalog.tekton.dev
spec:
  group: catalog.tekton.dev
  names:
    kind: Catalog
    plural: catalogs
  scope: ""
  validation:
    openAPIV3Schema:
      description: Catalog is the Schema for the catalogs API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: CatalogSpec defines the desired state of Catalog
          properties:
            contextPath:
              type: string
            revision:
              type: string
            url:
              type: string
          required:
          - url
          type: object
        status:
          description: CatalogStatus defines the observed state of Catalog
          properties:
            clustertasks:
              items:
                properties:
                  name:
                    type: string
                  versions:
                    items:
                      type: string
                    type: array
                required:
                - name
                - versions
                type: object
              type: array
            condition:
              description: CatalogCondition represents the current condition of the
                catalog
              properties:
                code:
                  type: string
                details:
                  type: string
              required:
              - code
              type: object
            lastSynced:
              description: Information when was the last time the job was successfully
                scheduled.
              properties:
                revision:
                  type: string
                time:
                  description: Information when was the last time the job was successfully
                    scheduled.
                  format: date-time
                  type: string
              type: object
            tasks:
              items:
                properties:
                  name:
                    type: string
                  versions:
                    items:
                      type: string
                    type: array
                required:
                - name
                - versions
                type: object
              type: array
          type: object
      type: object
  versions:
  - name: v1alpha1
    served: true
    storage: true
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
