---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: api
  namespace: tekton-hub-preview
spec:
  to:
    kind: Service
    name: api
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
