---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui
  namespace: tekton-hub
  labels:
    app: ui
spec:
  selector:
    matchLabels:
      app: ui
  template:
    metadata:
      name: ui
      labels:
        app: ui
    spec:
      containers:
        - name: ui
          image: quay.io/sthaha/tekton-hub-ui
          env:
            - name: API_URL
              valueFrom:
                configMapKeyRef:
                  name: ui
                  key: API_URL
            - name: GH_CLIENT_ID
              valueFrom:
                configMapKeyRef:
                  name: ui
                  key: GH_CLIENT_ID
          ports:
            - containerPort: 8080
              protocol: TCP
